# Generated by Django 4.2.4 on 2023-08-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingresa el nombre de la biblioteca.', max_length=50)),
                ('direccion', models.CharField(help_text='Ingresa la dirección de la biblioteca', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del libro', max_length=50)),
                ('isbn', models.CharField(help_text='Ingrese el número ISBN del libro', max_length=100)),
                ('autor', models.CharField(help_text='Ingresa el autor del libro', max_length=50)),
                ('done', models.BooleanField(help_text='Ingrese si el libro esta prestado o en sala', max_length=8)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.biblioteca')),
            ],
        ),
    ]
